Check for presence of `$path/functions/__git.init.fish` before sourcing it
jhillyerd/plugin-git pull request #103
Opened 2023-11-06 05:20 UTC by hexclover

Closes #102.

Test 1: On a home-manager enabled NixOS with fish as default shell, the `gst` abbreviation works, and SSH with jump host works.
Test 2: On an Arch system with fish as default shell and OMF, the `gst` abbreviation works.

2023-11-06 18:40 UTC, jhillyerd requested changes
Can you add a comment or two explaining the why & how of this, it's going to be non-obvious to anyone that isn't familiar with how home-manager works, and I'm unlikely to remember either.

2023-11-07 16:25 UTC, PaulGrandperrin commented
I tried this PR:
```nix
        {
          name = "plugin-git"; # git abbrs
          #src = plugin-git.src;
          src = pkgs.fetchFromGitHub {
            owner = "hexclover";
            repo = "plugin-git";
            rev = "master";
            sha256 = "sha256-efKPbsXxjHm1wVWPJCV8teG4DgZN5dshEzX8PWuhKo4";
          };
        }
```
and it fixes `scp` for me! thanks :)

2023-11-07 16:27 UTC, PaulGrandperrin commented
I'm using NixOS + HM on unstable  FWIW

2023-11-07 18:12 UTC, jhillyerd approved these changes

2023-11-07 18:12 UTC, merged

2023-11-07 18:12 UTC, jhillyerd commented
Thanks!

2024-02-09 22:00 UTC, GaetanLepage commented
Thanks for the fix ! 
Can you make a git release that would then ship this fix please ?
The `plugin-git` version in nixpkgs is still v0.1 (Feb. 2023)